baseurl = "https://blog.charleslaw.me/"
languageCode = "en-us"
Title = "Claw Journal"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Copyright 2020"
publishDir = ".."
theme = "hugo_theme_pickles"

# Google Analytics API key.
googleAnalytics = "UA-168736733-1"

[params]
  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and
  # footer
  #twitter = "Your Twitter username"
  #facebook = "Your Facebook username"
  #instagram = "Your Instagram username"
  #googleplus = "Your Google+ account URL" # https://plus.google.com/u/0/xxxxxx
  github = "charleslaw"
  #gitlab = "Your GitLab username"
  #npm = "Your npm username"
  #codepen = "Your CodePen username"
  #dribbble = "Your Dribbble username"
  #fivehundredpx = "Your 500px username" # 500px
  #flickr = "Your Flickr username"
  #pinterest = "Your Pinterest username"
  #tumblr = "Your Tumblr username"
  #vimeo = "Your Vimeo username"
  #youtube = "Your YouTube username"
  linkedin = "charleslaw1"
  #medium = "Your Medium username"
  # Disqus shortname
  #disqus = ""
  author = "Charles Law"
  authorwebsite = "https://charleslaw.me"
  avatar = "https://s.gravatar.com/avatar/99836456ec6d87389df32d2cdcf8d825?s=80"
  contact = "https://charleslaw.me/contact/"
  #bio = ""
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "discovering and building the future"
  # Logo image. This is displayed ogp image.
  # logo = "/path/to/logo"
  favicon = "https://charleslaw.me/favicon.ico"
  custom_css = ["/static/css/custom.css"]

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[[menu.main]]
    name = "Website"
    url = "https://charleslaw.me"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 4

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
